# https://github.com/sasstools/sass-lint/tree/master/docs/rules
# 0: null
# 1: warning
# 2: error

options:
  merge-default-rules: false
  formatter: html
  output-file: 'linters/sass-lint.html'
  max-warnings: 150

files:
  include: 'scss/**/*.scss'

rules:
  brace-style: 1tbs
  class-name-format:
    - 1
    - convention: '([a-z0-9]+-?)+'
  clean-import-paths:
    - 1
    - filename-extension: false
      leading-underscore: false
  declarations-before-nesting: true
  empty-line-between-blocks:
    - 1
    - ignore-single-line-rulesets: true
  extends-before-mixins: 2
  extends-before-declarations: 2
  final-newline:
    - 1
    - include: true
  hex-length:
    - 1
    - style: long
  hex-notation:
    - 1
    - style: lowercase
  indentation:
    - 2
    - size: 4
  mixin-name-format:
    - 1
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  mixins-before-declarations:
    - 0
    - exclude:
        - breakpoint
  nesting-depth:
    - 2
    - max-depth: 3
  no-css-comments: 1
  no-debug: 1
  no-ids: 2
  no-important: 0
  no-invalid-hex: 2
  no-warn: 0
  placeholder-in-extend: 0
  property-sort-order:
    - 0
    - order:
        - display
        - position
  space-after-comma: 2
  space-before-bang: 1
  space-before-brace: 2
  space-before-colon: 2
  trailing-semicolon: 2
  url-quotes:
    - 1
    - style: single
  zero-unit: 0
